spring:
  datasource:
    type: com.alibaba.druid.pool.DruidDataSource
    username: root
    password: 123456
    url: jdbc:mysql://82.156.187.67:3306/liuran?useUnicode=true&characterEncoding=UTF-8&serverTimezone=Asia/Shanghai
  rabbitmq:
    username: guest
    password: guest
    host: 82.156.187.67
    publisher-confirms: true
    publisher-returns: true
  redis:
    host: 82.156.187.67
    database: 3
    port: 36379
    password: 123456
  cache:
    cache-names: menus_cache
server:
  port: 1111
  compression:
    enabled: true
  servlet:
    context-path: /web
    multipart:
      enabled: true #开启文件上传
      max-file-size: 100MB #限制文件上传大小为10M
      max-request-size: 100MB
fastdfs:
  nginx:
    host: http://82.156.187.67/
file:
  type: minio
minio:
  endpoint: http://82.156.187.67:9000/
  accessKey: liuranandkexinlan
  secretKey: liuranandkexinlan